version: '3.8'

services:
  app-1:
    container_name: app-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm run watch:app-1

  app-2:
    container_name: app-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm run watch:app-2
